version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    working_directory: ~/ui
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
      - restore_cache:
            keys:
                - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
            name: 'Install project dependencies'
            command: npm install
      - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
                - ./node_modules
